export const TRACKER_ID_PROVIDER = 'TRACKER_ID_PROVIDER';
export const LOGGER_PROVIDER = 'LOGGER_PROVIDER';

export const NEW_FILE_CONVERTER_QUEUE_PUBLISHER_PROVIDER =
  'NEW_FILE_CONVERTER_QUEUE_PUBLISHER_PROVIDER';

export const CONVERTION_SUCCESS_QUEUE_PUBLISHER_ADAPTER =
  'CONVERTION_SUCCESS_QUEUE_PUBLISHER_ADAPTER';
