version: "3"

services:

  # app:
  #   restart: always
  #   build:
  #     context: .
  #   ports:
  #     - 3000:3000
  #   container_name: api_auth_service_microservice
  #   env_file:
  #    - .env

  database:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
   