version: "3"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  
  queue:
    image: redis
    ports: 
      - 6379:6379
    container_name: queue_redis