version: "3"

services:

  app:
    restart: always
    build:
      context: .
    container_name: app_notification
    env_file:
     - .env
   
  queue:
    image: redis
    ports: 
      - 6379:6379
    container_name: queue_redis